#!/usr/bin/python

from funcs import *
import os
import sys
import argparse

def main():
    # Parse command line args
    parser = argparse.ArgumentParser(prog='ocr')
    parser.add_argument('-b', '--bmp', type=str, default=None,
        help='convert lone image OR images in formatted directory to bmps')
    parser.add_argument('-s', '--side', type=int, default=10,
        help='length of side of bmp image (default is 10)')
    parser.add_argument('-l', '--highlo', type=int, default=60,
        help='high-pass/low-pass threshold (default is 60)')
    parser.add_argument('-c', '--clear', type=bool, default=False,
        help='flag to delete BMPs folder after reading image (default is False)')
    args = parser.parse_args()

    # Convert folder of images to formatted BMPs
    if args.bmp:
        bmpFolder = 'Bmps'
        if os.path.isdir(args.bmp):
            rawFolder = args.bmp.split('.')[0]
            createBmps(rawFolder, bmpFolder, args.side)
        else:
            bmpFolder = args.bmp + 'Bmps'
            fullImgBmp(args.bmp, bmpFolder, args.side, args.highlo)

        # Clear formatted BMPs
        if args.clear:
            shutil.rmtree(bmpFolder)


if __name__ == '__main__':
    main()
