#!/usr/bin/python

from funcs import *
import os
import sys
import argparse

def main():
    # Parse command line args
    parser = argparse.ArgumentParser(prog='ocr')
    parser.add_argument('-i', '--iters', type=str, default=200,
        help='number of training iterations to run over provided training set (default is 300)')
    parser.add_argument('-t', '--train', type=str, nargs='+',
        help='folder with training inputs')
    parser.add_argument('-r', '--read', type=str,
        help='folder with images to read')
    parser.add_argument('-w', '--weights', type=str,
        help='starting weights file (default is random starting weights)')
    parser.add_argument('-a', '--alpha', type=str, default=0.01,
        help='the alpha value (default is 0.01)')
    parser.add_argument('-b', '--bmp', type=str, default=None,
        help='convert images in directory to bmps')
    parser.add_argument('-s', '--side', type=int, default=10,
        help='length of side of bmp image (default is 10)')
    parser.add_argument('-l', '--highlo', type=int, default=60,
        help='high-pass/low-pass threshold (default is 60)')
    parser.add_argument('-c', '--clear', type=bool, default=True,
        help='flag to delete BMPs folder after reading image (default is True)')
    args = parser.parse_args()

    # Convert folder of images to formatted BMPs
    if args.bmp:
        rawFolder = args.bmp.split('.')[0]
        createBmps(rawFolder, rawFolder + 'Bmps', args.side)

    # OCR an image
    annArgs = ['ANN/exe','-n',str(args.iters)]
    bmpFolder = None
    if args.train:
        annArgs.append('-r')
        annArgs.extend(args.train)
    if args.weights:
        annArgs.append('-w')
        annArgs.append(args.weights)
    if args.read:
        bmpFolder = args.read.split('.')[0] + 'Bmps'
        fullImgBmps(args.read, bmpFolder, args.side, args.highlo) 
        annArgs.append('-p')
        annArgs.extend( [str(f) for f in glob.glob(bmpFolder+'/*')] ) 

    # Run the ANN
    if args.read or args.train:
        if args.read:
            print(runANN(annArgs, True))
        else:
            runANN(annArgs)

        # Clear formatted BMPs
        if args.clear:
            shutil.rmtree(bmpFolder)


if __name__ == '__main__':
    main()
